#!/bin/bash
# ──────────────────────────────────────────────────────────
# [Clean Architecture] Infrastructure Layer - Image Signing
#
# 역할: FIT 이미지 서명 + dm-verity 해시 트리 생성
# 수행범위: 커널/DTB/램디스크 서명, rootfs verity 생성
# 의존방향: mkimage, openssl, veritysetup
# SOLID: SRP — 이미지 서명만 담당
#
# 사용법: ./tools/sign-image.sh <rootfs-image> [output-dir]
# ──────────────────────────────────────────────────────────
set -euo pipefail

ROOTFS="${1:-}"
OUTPUT_DIR="${2:-build/signed}"
KEY_DIR="board/bpi-f3/keys"
KEY_NAME="zylos-boot-key"
ITS_FILE="board/bpi-f3/fit-image.its"

if [ -z "$ROOTFS" ]; then
    echo "Usage: $0 <rootfs-image> [output-dir]"
    echo ""
    echo "Required files:"
    echo "  vmlinuz                      — Compressed kernel"
    echo "  system/dts/bpi-f3-zyl.dtb    — Device tree blob"
    echo "  initramfs.cpio.gz            — Initial ramdisk"
    echo "  <rootfs-image>               — Root filesystem image"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

echo "═══ Zyl OS Image Signing ═══"
echo ""

# ── 1. Verify key exists ──
if [ ! -f "$KEY_DIR/$KEY_NAME.key" ]; then
    echo "✗ Signing key not found: $KEY_DIR/$KEY_NAME.key"
    echo "  Run: ./tools/gen-boot-keys.sh"
    exit 1
fi

# ── 2. Sign FIT image (kernel + DTB + ramdisk) ──
echo "▸ [1/4] Signing FIT image..."

if [ ! -f "vmlinuz" ] || [ ! -f "initramfs.cpio.gz" ]; then
    echo "⚠ vmlinuz or initramfs.cpio.gz not found — skipping FIT signing"
    echo "  (These are produced by the kernel build)"
else
    mkimage -f "$ITS_FILE" \
        -k "$KEY_DIR" \
        -K "$OUTPUT_DIR/u-boot.dtb" \
        -r \
        "$OUTPUT_DIR/fit-image.itb"

    echo "  ✓ FIT image: $OUTPUT_DIR/fit-image.itb"

    # Verify signature
    mkimage -F -k "$KEY_DIR" -K "$OUTPUT_DIR/u-boot.dtb" -r "$OUTPUT_DIR/fit-image.itb"
    echo "  ✓ FIT signature verified"
fi

# ── 3. Generate dm-verity hash tree ──
echo "▸ [2/4] Generating dm-verity hash tree..."

if [ ! -f "$ROOTFS" ]; then
    echo "✗ Root filesystem not found: $ROOTFS"
    exit 1
fi

# veritysetup format: creates hash tree + outputs root hash
VERITY_OUTPUT=$(veritysetup format "$ROOTFS" "$OUTPUT_DIR/verity-hashtree.img" 2>&1)
ROOT_HASH=$(echo "$VERITY_OUTPUT" | grep "Root hash:" | awk '{print $NF}')
SALT=$(echo "$VERITY_OUTPUT" | grep "Salt:" | awk '{print $NF}')
DATA_BLOCKS=$(echo "$VERITY_OUTPUT" | grep "Data blocks:" | awk '{print $NF}')
HASH_OFFSET=$(echo "$VERITY_OUTPUT" | grep "Hash block size:" | awk '{print $NF}')

if [ -z "$ROOT_HASH" ]; then
    echo "✗ veritysetup failed"
    exit 1
fi

echo "  ✓ Root hash: $ROOT_HASH"
echo "  ✓ Hash tree: $OUTPUT_DIR/verity-hashtree.img"

# Save verity parameters for kernel cmdline
cat > "$OUTPUT_DIR/verity-params.txt" <<EOF
# dm-verity parameters for kernel cmdline
# Generated by sign-image.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
ROOT_HASH=$ROOT_HASH
SALT=$SALT
DATA_BLOCKS=$DATA_BLOCKS
VERITY_HASHTREE=$OUTPUT_DIR/verity-hashtree.img
EOF

echo "  ✓ Parameters: $OUTPUT_DIR/verity-params.txt"

# ── 4. Generate kernel cmdline with verity ──
echo "▸ [3/4] Generating kernel cmdline..."

cat > "$OUTPUT_DIR/cmdline.txt" <<EOF
root=/dev/dm-0 ro
dm-mod.create="verity,,,ro,0 $DATA_BLOCKS verity 1 /dev/mmcblk0p2 /dev/mmcblk0p3 4096 4096 $DATA_BLOCKS 0 sha256 $ROOT_HASH $SALT"
console=ttyS0,115200
zyl.slot=a
quiet splash
EOF

echo "  ✓ Cmdline: $OUTPUT_DIR/cmdline.txt"

# ── 5. Generate SHA-256 manifest of all outputs ──
echo "▸ [4/4] Generating manifest..."

cd "$OUTPUT_DIR"
sha256sum *.itb *.img *.txt 2>/dev/null > MANIFEST.sha256 || true
cd - > /dev/null

echo "  ✓ Manifest: $OUTPUT_DIR/MANIFEST.sha256"

echo ""
echo "═══ Signing Complete ═══"
echo ""
echo "Flash instructions:"
echo "  1. Write fit-image.itb to boot partition"
echo "  2. Write rootfs to partition A (mmcblk0p2)"
echo "  3. Write verity-hashtree.img to partition B (mmcblk0p3)"
echo "  4. Set U-Boot env: bootcmd='bootm \${fit_addr}'"
echo ""
echo "⚠ Keep $KEY_DIR/$KEY_NAME.key in a hardware security module (HSM)"
echo "  or encrypted offline storage. NEVER commit to source control."
